ALTER SESSION SET CURRENT_SCHEMA = MISREAD;
SET DEFINE OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;

DROP TABLE T_DWH_12FREE_SUMMARY;

CREATE TABLE T_DWH_12FREE_SUMMARY
(
F_USER_ID VARCHAR2(40)  NOT NULL,
F_TIME_PERIOD VARCHAR2(20)  NOT NULL,
F_TOTAL_PRIZE_WIN_COUNT NUMBER,
F_TOTAL_PRIZE_WIN_CASH_AMT_GBP NUMBER,
F_TOTAL_PRIZE_WIN_FREEBET_AMT_GBP NUMBER,
F_TOTAL_CORRECT_SCORES_COUNT NUMBER,
F_FALLBACK NUMBER,
F_PLAYEDPROMOTIONYN CHAR(1),
F_CREATED_DATE DATE  NOT NULL,
CONSTRAINT PK_VP_12FREE PRIMARY KEY (F_USER_ID, F_TIME_PERIOD) 
)
PARTITION BY RANGE (F_CREATED_DATE)
(PARTITION P_VP_12FREE_SUMMARY VALUES LESS THAN (TO_DATE('31-DEC-2999','DD-MON-YYYY')) TABLESPACE TS_SUMMARY;

/
COMMENT ON TABLE T_DWH_12FREE_SUMMARY IS 	
    'This table holds 1-2-FREE bonus consolidation info for a player';

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY.F_USER_ID IS 	
    'Holds the player account name for this record';

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY.F_TIME_PERIOD IS 	
    'Holds the timeperiod for which this bonus calculation is done';

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY.F_TOTAL_PRIZE_WIN_COUNT IS 	
    'Holds the number of times the prizes won by this player in this promotion';

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY.F_TOTAL_PRIZE_WIN_CASH_AMT_GBP IS 	
    'Holds the total amount won by this player in 1-2-FREE promotion';
	
COMMENT ON COLUMN T_DWH_12FREE_SUMMARY.F_TOTAL_PRIZE_WIN_FREEBET_AMT_GBP IS 	
    'Holds the total free bet amount won by this player in 1-2-FREE promotion';

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY.F_TOTAL_CORRECT_SCORES_COUNT IS 	
    'Holds the number of times the player has provided the correct predictions';	

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY.F_FALLBACK IS 	
    'Holds the flag which specifies whether to look for fallback or not from BI perspective';	
	
COMMENT ON COLUMN T_DWH_12FREE_SUMMARY.F_PLAYEDPROMOTIONYN IS 	
    'Holds the flag which specifies whether player participated in the promotion or not';		

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY.F_CREATED_DATE IS 	
    'Holds the Date on which this record is created';		


GRANT SELECT ON T_DWH_12FREE_SUMMARY TO PPOKEROPS
/	

DROP TABLE T_DWH_CORRECT4_SUMMARY
/


CREATE TABLE T_DWH_CORRECT4_SUMMARY
(
F_USER_ID VARCHAR2(40) NOT NULL,
F_TIME_PERIOD VARCHAR2(20) NOT NULL,
F_TOTAL_PRIZE_WIN_COUNT NUMBER,
F_TOTAL_PRIZE_WIN_CASH_AMT_GBP NUMBER,
F_TOTAL_PRIZE_WIN_FREEBET_AMT_GBP NUMBER,
F_TOTAL_CORRECT_SCORES_COUNT NUMBER,
F_FALLBACK NUMBER,
F_PLAYEDPROMOTIONYN CHAR(1),
F_CREATED_DATE DATE NOT NULL,
CONSTRAINT PK_VP_CORRECT4 PRIMARY KEY (F_USER_ID, F_TIME_PERIOD)
)PARTITION BY RANGE (F_CREATED_DATE)
(PARTITION P_VP_CORRECT4_SUMMARY VALUES LESS THAN (TO_DATE('31-DEC-2999','DD-MON-YYYY')) TABLESPACE TS_SUMMARY;

COMMENT ON TABLE T_DWH_CORRECT4_SUMMARY IS 	
    'This table holds Correct4 bonus consolidation info for a player';

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY.F_USER_ID IS 	
    'Holds the player account name for this record';

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY.F_TIME_PERIOD IS 	
    'Holds the timeperiod for which this bonus calculation is done';
	
COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY.F_TOTAL_PRIZE_WIN_COUNT IS 	
    'Holds the number of times the prizes won by this player in this promotion';

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY.F_TOTAL_PRIZE_WIN_CASH_AMT_GBP IS 	
    'Holds the total amount won by this player in Correct4 promotion';
	
COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY.F_TOTAL_PRIZE_WIN_FREEBET_AMT_GBP IS 	
    'Holds the total free bet amount won by this player in Correct4 promotion';

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY.F_TOTAL_CORRECT_SCORES_COUNT IS 	
    'Holds the number of times the player has provided the correct predictions';	

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY.F_FALLBACK IS 	
    'Holds the flag which specifies whether to look for fallback or not from BI perspective';	
	
COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY.F_PLAYEDPROMOTIONYN IS 	
    'Holds the flag which specifies whether player participated in the promotion or not';		

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY.F_CREATED_DATE IS 	
    'Holds the Date on which this record is created';	


GRANT SELECT ON T_DWH_CORRECT4_SUMMARY TO PPOKEROPS
/	

DROP TABLE T_DWH_CLRACING_SUMMARY
/


CREATE TABLE T_DWH_CLRACING_SUMMARY
(
F_USER_ID VARCHAR2(40) NOT NULL,
F_TIME_PERIOD VARCHAR2(20) NOT NULL,
F_TOTAL_PRIZE_WIN_CASH_AMT_GBP NUMBER,
F_FALLBACK NUMBER,
F_PLAYEDPROMOTIONYN CHAR(1),
F_CREATED_DATE DATE NOT NULL,
CONSTRAINT PK_VP_CLRACING PRIMARY KEY (F_USER_ID, F_TIME_PERIOD)
)PARTITION BY RANGE (F_CREATED_DATE)
(PARTITION P_VP_CLRACING_SUMMARY VALUES LESS THAN (TO_DATE('31-DEC-2999','DD-MON-YYYY')) TABLESPACE TS_SUMMARY;

COMMENT ON TABLE T_DWH_CLRACING_SUMMARY IS 	
    'This table holds Racing Super Series bonus consolidation info for a player';

COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY.F_USER_ID IS 	
    'Holds the player account name for this record';

COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY.F_TIME_PERIOD IS 	
    'Holds the timeperiod for which this bonus calculation is done';

COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY.F_TOTAL_PRIZE_WIN_CASH_AMT_GBP IS 	
    'Holds the total amount won by this player in Racing Super Series promotion';
	
COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY.F_FALLBACK IS 	
    'Holds the flag which specifies whether to look for fallback or not from BI perspective';	
	
COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY.F_PLAYEDPROMOTIONYN IS 	
    'Holds the flag which specifies whether player participated in the promotion or not';		

COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY.F_CREATED_DATE IS 	
    'Holds the Date on which this record is created';	

GRANT SELECT ON T_DWH_CLRACING_SUMMARY TO PPOKEROPS
/	

DROP TABLE T_DWH_FALLBACK_SUMMARY
/
 
CREATE TABLE T_DWH_FALLBACK_SUMMARY
(
F_ID INTEGER GENERATED ALWAYS AS IDENTITY,
F_PROPOSITION_NAME VARCHAR2(100) NOT NULL,
F_TIME_PERIOD VARCHAR2(20) NOT NULL,
F_FALLBACK_KEY VARCHAR2(500) NOT NULL,
F_FALLBACK_VALUE NUMBER,
F_CREATED_DATE DATE,
CONSTRAINT PK_VP_FALBCK_SUMM PRIMARY KEY (F_ID)
)PARTITION BY RANGE (F_CREATED_DATE)
(PARTITION P_VP_FALBCK_SUMM VALUES LESS THAN (TO_DATE('31-DEC-2999','DD-MON-YYYY')) TABLESPACE TS_SUMMARY;

CREATE INDEX IDX_VP_FALBCK_SUMM ON T_DWH_FALLBACK_SUMMARY (F_TIME_PERIOD) LOCAL TABLESPACE TS_TX_IDX
/

COMMENT ON TABLE T_DWH_FALLBACK_SUMMARY IS 	
    'This table holds Fallback Details for all the promotions';
	
COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY.F_ID IS 	
    'Holds unique sequence id for each of the record';	

COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY.F_PROPOSITION_NAME IS 	
    'Holds the name of the promotion name for which this record stands for';	

COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY.F_TIME_PERIOD IS 	
    'Holds the timeperiod for which this promotion calculation is done';		
	
COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY.F_FALLBACK_KEY IS 	
    'Holds the Fallback Key of the promotion';			

COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY.F_FALLBACK_VALUE IS 	
    'Holds the Fallback Value of the promotion and the fallback key';			

COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY.F_CREATED_DATE IS 	
    'Holds the Date on which this record is created';	

GRANT SELECT ON T_DWH_FALLBACK_SUMMARY TO PPOKEROPS
/	

-------------------------------------------------------------------------------------------
------------------------------------STAGE TABLES-------------------------------------------
-------------------------------------------------------------------------------------------
DROP TABLE T_DWH_12FREE_SUMMARY_STG
/


CREATE TABLE T_DWH_12FREE_SUMMARY_STG
(
F_USER_ID VARCHAR2(40) NOT NULL,
F_TIME_PERIOD VARCHAR2(20)  NOT NULL,
F_TOTAL_PRIZE_WIN_COUNT NUMBER,
F_TOTAL_PRIZE_WIN_CASH_AMT_GBP NUMBER,
F_TOTAL_PRIZE_WIN_FREEBET_AMT_GBP NUMBER,
F_TOTAL_CORRECT_SCORES_COUNT NUMBER,
F_FALLBACK NUMBER,
F_PLAYEDPROMOTIONYN CHAR(1),
F_CREATED_DATE DATE  NOT NULL,
CONSTRAINT PK_VP_12FREE_STG PRIMARY KEY (F_USER_ID, F_TIME_PERIOD)
)TABLESPACE TS_SUMMARY;


COMMENT ON TABLE T_DWH_12FREE_SUMMARY_STG IS 	
    'This table holds 1-2-FREE bonus consolidation info for a player';

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY_STG.F_USER_ID IS 	
    'Holds the player account name for this record';

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY_STG.F_TIME_PERIOD IS 	
    'Holds the timeperiod for which this bonus calculation is done';

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY_STG.F_TOTAL_PRIZE_WIN_COUNT IS 	
    'Holds the number of times the prizes won by this player in this promotion';

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY_STG.F_TOTAL_PRIZE_WIN_CASH_AMT_GBP IS 	
    'Holds the total amount won by this player in 1-2-FREE promotion';
	
COMMENT ON COLUMN T_DWH_12FREE_SUMMARY_STG.F_TOTAL_PRIZE_WIN_FREEBET_AMT_GBP IS 	
    'Holds the total free bet amount won by this player in 1-2-FREE promotion';

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY_STG.F_TOTAL_CORRECT_SCORES_COUNT IS 	
    'Holds the number of times the player has provided the correct predictions';	

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY_STG.F_FALLBACK IS 	
    'Holds the flag which specifies whether to look for fallback or not from BI perspective';	
	
COMMENT ON COLUMN T_DWH_12FREE_SUMMARY_STG.F_PLAYEDPROMOTIONYN IS 	
    'Holds the flag which specifies whether player participated in the promotion or not';		

COMMENT ON COLUMN T_DWH_12FREE_SUMMARY_STG.F_CREATED_DATE IS 	
    'Holds the Date on which this record is created';		


GRANT SELECT ON T_DWH_12FREE_SUMMARY_STG TO PPOKEROPS
/	

DROP TABLE T_DWH_CORRECT4_SUMMARY_STG
/

CREATE TABLE T_DWH_CORRECT4_SUMMARY_STG
(
F_USER_ID VARCHAR2(40)  NOT NULL,
F_TIME_PERIOD VARCHAR2(20)  NOT NULL,
F_TOTAL_PRIZE_WIN_COUNT NUMBER,
F_TOTAL_PRIZE_WIN_CASH_AMT_GBP NUMBER,
F_TOTAL_PRIZE_WIN_FREEBET_AMT_GBP NUMBER,
F_TOTAL_CORRECT_SCORES_COUNT NUMBER,
F_FALLBACK NUMBER,
F_PLAYEDPROMOTIONYN CHAR(1),
F_CREATED_DATE DATE  NOT NULL,
CONSTRAINT PK_VP_CORRECT4_STG PRIMARY KEY (F_USER_ID, F_TIME_PERIOD)
)TABLESPACE TS_SUMMARY;

COMMENT ON TABLE T_DWH_CORRECT4_SUMMARY_STG IS 	
    'This table holds Correct4 bonus consolidation info for a player';

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY_STG.F_USER_ID IS 	
    'Holds the player account name for this record';

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY_STG.F_TIME_PERIOD IS 	
    'Holds the timeperiod for which this bonus calculation is done';
	
COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY_STG.F_TOTAL_PRIZE_WIN_COUNT IS 	
    'Holds the number of times the prizes won by this player in this promotion';

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY_STG.F_TOTAL_PRIZE_WIN_CASH_AMT_GBP IS 	
    'Holds the total amount won by this player in Correct4 promotion';
	
COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY_STG.F_TOTAL_PRIZE_WIN_FREEBET_AMT_GBP IS 	
    'Holds the total free bet amount won by this player in Correct4 promotion';

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY_STG.F_TOTAL_CORRECT_SCORES_COUNT IS 	
    'Holds the number of times the player has provided the correct predictions';	

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY_STG.F_FALLBACK IS 	
    'Holds the flag which specifies whether to look for fallback or not from BI perspective';	
	
COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY_STG.F_PLAYEDPROMOTIONYN IS 	
    'Holds the flag which specifies whether player participated in the promotion or not';		

COMMENT ON COLUMN T_DWH_CORRECT4_SUMMARY_STG.F_CREATED_DATE IS 	
    'Holds the Date on which this record is created';	


GRANT SELECT ON T_DWH_CORRECT4_SUMMARY_STG TO PPOKEROPS
/	


DROP TABLE T_DWH_CLRACING_SUMMARY_STG
/

CREATE TABLE T_DWH_CLRACING_SUMMARY_STG
(
F_USER_ID VARCHAR2(40)  NOT NULL,
F_TIME_PERIOD VARCHAR2(20)  NOT NULL,
F_TOTAL_PRIZE_WIN_CASH_AMT_GBP NUMBER,
F_FALLBACK NUMBER,
F_PLAYEDPROMOTIONYN CHAR(1),
F_CREATED_DATE DATE  NOT NULL,
CONSTRAINT PK_VP_CLRACING_STG PRIMARY KEY (F_USER_ID,F_TIME_PERIOD)
)TABLESPACE TS_SUMMARY;

COMMENT ON TABLE T_DWH_CLRACING_SUMMARY_STG IS 	
    'This table holds Racing Super Series bonus consolidation info for a player';

COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY_STG.F_USER_ID IS 	
    'Holds the player account name for this record';

COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY_STG.F_TIME_PERIOD IS 	
    'Holds the timeperiod for which this bonus calculation is done';

COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY_STG.F_TOTAL_PRIZE_WIN_CASH_AMT_GBP IS 	
    'Holds the total amount won by this player in Racing Super Series promotion';
	
COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY_STG.F_FALLBACK IS 	
    'Holds the flag which specifies whether to look for fallback or not from BI perspective';	
	
COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY_STG.F_PLAYEDPROMOTIONYN IS 	
    'Holds the flag which specifies whether player participated in the promotion or not';		

COMMENT ON COLUMN T_DWH_CLRACING_SUMMARY_STG.F_CREATED_DATE IS 	
    'Holds the Date on which this record is created';	

GRANT SELECT ON T_DWH_CLRACING_SUMMARY_STG TO PPOKEROPS
/	

DROP TABLE T_DWH_FALLBACK_SUMMARY_STG
/


CREATE TABLE T_DWH_FALLBACK_SUMMARY_STG
(
F_ID INTEGER GENERATED ALWAYS AS IDENTITY,
F_PROPOSITION_NAME VARCHAR2(100)  NOT NULL,
F_TIME_PERIOD VARCHAR2(20)  NOT NULL,
F_FALLBACK_KEY VARCHAR2(500)  NOT NULL,
F_FALLBACK_VALUE NUMBER,
F_CREATED_DATE DATE  NOT NULL,
CONSTRAINT PK_VP_FALBCK_SUMM_STG PRIMARY KEY (F_ID)
)TABLESPACE TS_SUMMARY;

CREATE INDEX IDX_VP_FALBCK_SUMM_STG ON T_DWH_FALLBACK_SUMMARY_STG (F_TIME_PERIOD) TABLESPACE TS_TX_IDX;
/

COMMENT ON TABLE T_DWH_FALLBACK_SUMMARY_STG IS 	
    'This table holds Fallback Details for all the promotions';
	
COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY_STG.F_ID IS 	
    'Holds unique sequence id for each of the record';	

COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY_STG.F_PROPOSITION_NAME IS 	
    'Holds the name of the promotion name for which this record stands for';	

COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY_STG.F_TIME_PERIOD IS 	
    'Holds the timeperiod for which this promotion calculation is done';		
	
COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY_STG.F_FALLBACK_KEY IS 	
    'Holds the Fallback Key of the promotion';			

COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY_STG.F_FALLBACK_VALUE IS 	
    'Holds the Fallback Value of the promotion and the fallback key';			

COMMENT ON COLUMN T_DWH_FALLBACK_SUMMARY_STG.F_CREATED_DATE IS 	
    'Holds the Date on which this record is created';	

GRANT SELECT ON T_DWH_FALLBACK_SUMMARY_STG TO PPOKEROPS
/

ALTER SESSION SET CURRENT_SCHEMA = PPOKEROPS;

DROP SYNONYM T_DWH_12FREE_SUMMARY
/
CREATE SYNONYM T_DWH_12FREE_SUMMARY FOR MISREAD.T_DWH_12FREE_SUMMARY
/
DROP SYNONYM T_DWH_CORRECT4_SUMMARY
/
CREATE SYNONYM T_DWH_CORRECT4_SUMMARY FOR MISREAD.T_DWH_CORRECT4_SUMMARY
/
DROP SYNONYM T_DWH_CLRACING_SUMMARY
/
CREATE SYNONYM T_DWH_CLRACING_SUMMARY FOR MISREAD.T_DWH_CLRACING_SUMMARY
/
DROP SYNONYM T_DWH_FALLBACK_SUMMARY
/
CREATE SYNONYM T_DWH_FALLBACK_SUMMARY FOR MISREAD.T_DWH_FALLBACK_SUMMARY
/
DROP SYNONYM T_DWH_12FREE_SUMMARY_STG
/
CREATE SYNONYM T_DWH_12FREE_SUMMARY_STG FOR MISREAD.T_DWH_12FREE_SUMMARY_STG
/
DROP SYNONYM T_DWH_CORRECT4_SUMMARY_STG
/
CREATE SYNONYM T_DWH_CORRECT4_SUMMARY_STG FOR MISREAD.T_DWH_CORRECT4_SUMMARY_STG
/
DROP SYNONYM T_DWH_CLRACING_SUMMARY_STG
/
CREATE SYNONYM T_DWH_CLRACING_SUMMARY_STG FOR MISREAD.T_DWH_CLRACING_SUMMARY_STG
/
DROP SYNONYM T_DWH_FALLBACK_SUMMARY_STG
/
CREATE SYNONYM T_DWH_FALLBACK_SUMMARY_STG FOR MISREAD.T_DWH_FALLBACK_SUMMARY_STG
/

